name: CI

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - Upgrade
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write

env:
  CI: true
  NODE_ENV: development

jobs:
  test:
    name: CI for Node.js ${{ matrix.node }} on ${{ matrix.os }} with ${{ matrix.packageManager }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - lts/hydrogen
          - lts/iron
          - current
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        packageManager:
          - npm
          - yarn
          - pnpm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
        if: ${{ matrix.packageManager == 'pnpm' }}

      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Install dependencies with npm
        if: ${{ matrix.packageManager == 'npm' }}
        run: npm install

      - name: Install dependencies with yarn
        if: ${{ matrix.packageManager == 'yarn' }}
        run: yarn

      - name: Install dependencies with pnpm
        if: ${{ matrix.packageManager == 'pnpm' }}
        run: pnpm install

      - name: Try format
        run: ${{ matrix.packageManager }} run format

      - name: Try lint
        run: ${{ matrix.packageManager }} run lint

      - name: Try build
        run: ${{ matrix.packageManager }} run build

      - name: Run tests with npm
        if: ${{ matrix.packageManager == 'npm' }}
        run: npm test -- --reporters=default --reporters=jest-junit

      - name: Run tests with yarn/pnpm
        if: ${{ matrix.packageManager != 'npm' }}
        run: ${{ matrix.packageManager }} run test --reporters=default --reporters=jest-junit

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests for Node.js ${{ matrix.node }} on ${{ matrix.os }} with ${{ matrix.packageManager }}
          path: reports/jest-*.xml
          reporter: jest-junit
