name: Upgrade
on:
  # GitHub Actions use UTC time, so 21:00 means 5:00 UTC +8 Timezone
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:
permissions:
  contents: write
  actions: read
  checks: write
env:
  CI: true
  NODE_ENV: production
  COMMIT_MSG_BODY: ""
  GH_TOKEN: ${{ github.token }}
jobs:
  upgrade:
    name: Upgrade minor/patch version packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup jq
        uses: dcarbone/install-jq-action@v2.1.0
      - name: Setup node lts/*
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - name: Install dependencies
        run: npm ci --loglevel error --audit false --fund false
      - name: Check outdated packages
        run: echo "COMMIT_MSG_BODY=$(npm outdated --json | jq -cr 'to_entries[] | select( .value.current != .value.wanted ) | "- \(.key) \(.value.current) -> \(.value.wanted)" ')"  >> $GITHUB_ENV
      - name: Upgade packages if needed
        if: ${{ env.COMMIT_MSG_BODY != '' }}
        run: npm update
      - name: Commit lockfile if needed
        if: ${{ env.COMMIT_MSG_BODY != '' }}
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.event.sender.id }}+${{ github.event.sender.login }}@users.noreply.github.com
          git add package.json
          git add package-lock.json
          git commit -m "fix(deps): update all non-major dependencies" -m "${{ env.COMMIT_MSG_BODY }}" -m "by CI script"
          git push
